# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gbudgets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gentities', '0002_auto_20160725_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Thesaurus key')),
            ],
        ),
        migrations.CreateModel(
            name='Brecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Otros'), (1, 'Caracter\xedsticas t\xe9cnicas y de fabricaci\xf3n'), (2, 'Manual de colocaci\xf3n, uso y mantenimiento'), (3, 'Certificado/s de elementos y sistemas'), (4, 'Normativa y bibliograf\xeda'), (5, 'Tarifa de precios'), (6, 'Condiciones de venta'), (7, 'Carta de colores'), (8, '\xc1mbito de aplicaci\xf3n y criterios selecci\xf3n'), (9, 'C\xe1lculo de elementos y sistemas'), (10, 'Presentaci\xf3n, datos generales, objetivos, etc. de empresa'), (11, 'Certificado/s de empresa'), (12, 'Obras realizadas'), (13, 'Imagen')], verbose_name='Type of file')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='File description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Relative url')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=gbudgets.models.update_file, verbose_name='File related to the budget')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='File name')),
                ('content_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type of file')),
            ],
        ),
        migrations.CreateModel(
            name='Crecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=22, verbose_name='Code of the described concept')),
                ('unit', models.CharField(blank=True, max_length=7, null=True, verbose_name='Unit of measurement')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary of the concept')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Sin clasificar'), (1, 'Mano de obra'), (2, 'Maquinaria y medios auxiliares'), (3, 'Materiales'), (4, 'Componentes adicionales de residuo'), (5, 'Clasificaci\xf3n de residuo')], null=True, verbose_name='Type of concept')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Concept description')),
            ],
        ),
        migrations.CreateModel(
            name='Crecord_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price of the concept')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date when the price was defined')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord')),
            ],
        ),
        migrations.CreateModel(
            name='Crecord_synonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=22, verbose_name='Code of the described concept')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord')),
            ],
        ),
        migrations.CreateModel(
            name='Drecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0, verbose_name='Eficiency factor')),
                ('efficency', models.FloatField(default=1.0, verbose_name='N\xfamero de unidades, rendimiento o medici\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Drecord_percentage_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Percentage code')),
                ('drecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Drecord')),
            ],
        ),
        migrations.CreateModel(
            name='Erecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company code')),
                ('summary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre abreviado de la entidad')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo de la entidad')),
                ('type', models.CharField(choices=[('C', 'Central'), ('D', 'Delegaci\xf3n'), ('R', 'Representante')], default='C', max_length=4, verbose_name='Tipo de entidad')),
                ('subname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la delegaci\xf3n o representante')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direcci\xf3n de la entidad')),
                ('cp', models.IntegerField(blank=True, null=True, verbose_name='Postal code')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pa\xeds')),
                ('tel1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel1')),
                ('tel2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel2')),
                ('fax1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax1')),
                ('fax2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax2')),
                ('con1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto1')),
                ('con2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto2')),
                ('cif', models.CharField(blank=True, max_length=15, null=True, verbose_name='CIF')),
                ('web', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Gbudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title for the budget')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('gentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gentities.Gentity')),
            ],
        ),
        migrations.CreateModel(
            name='Grecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=60, null=True, verbose_name='Relative url to file')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord')),
                ('file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grecord_file', to='gbudgets.Budget_file')),
            ],
        ),
        migrations.CreateModel(
            name='Jrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_text', models.TextField(blank=True, null=True, verbose_name='Text of the paragraph')),
                ('htm_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jrecord_htm_file', to='gbudgets.Budget_file')),
            ],
        ),
        migrations.CreateModel(
            name='Krecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI', models.FloatField(default=0, verbose_name='Percentage CI')),
                ('GG', models.FloatField(default=0, verbose_name='Percentage GG')),
                ('BI', models.FloatField(default=0, verbose_name='Percentage BI')),
                ('BAJA', models.FloatField(default=0, verbose_name='Percentage BAJA')),
                ('IVA', models.FloatField(default=21, verbose_name='Percentage IVA')),
                ('DRC', models.IntegerField(default=3, verbose_name='... efficiency (or measure) in a chapter or subchapter break down.')),
                ('DC', models.IntegerField(default=2, verbose_name='... price of a chapter or subchapter.')),
                ('DFS', models.IntegerField(default=3, verbose_name='... factores de rendimiento de las unidades de obra y de los elementos compuestos.')),
                ('DRS', models.IntegerField(default=3, verbose_name='... rendimientos de las unidades de obra y de los elementos compuestos.')),
                ('DUO', models.IntegerField(default=2, verbose_name='... price of a unit of work.')),
                ('DI', models.IntegerField(default=2, verbose_name='... importes resultantes de multiplicar los rendimientos totales de los ...')),
                ('DES', models.IntegerField(default=2, verbose_name='... price of the simple elements.')),
                ('DN', models.IntegerField(default=2, verbose_name='... field "equal-size parts" in the measure lines.')),
                ('DD', models.IntegerField(default=2, verbose_name='... three dimensions in the measure lines.')),
                ('DS', models.IntegerField(default=2, verbose_name='... total sum of a measure.')),
                ('DSP', models.IntegerField(default=2, verbose_name='... l\xednea de subtotal de mediciones.')),
                ('DEC', models.IntegerField(default=2, verbose_name='... importe de los elementos compuestos.')),
                ('DIVISA', models.CharField(default='Euro', max_length=10, verbose_name='... monetary unit.')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget')),
            ],
        ),
        migrations.CreateModel(
            name='Lrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Scope statement section code')),
                ('section_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scope statement section title')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget')),
            ],
        ),
        migrations.CreateModel(
            name='Lrecord_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text asigned to the Scope stament section by de concept')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crecord', to='gbudgets.Crecord')),
                ('htm_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lrecord_htm_file', to='gbudgets.Budget_file')),
                ('lrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lrecord', to='gbudgets.Lrecord')),
                ('rtf_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lrecord_rtf_file', to='gbudgets.Budget_file')),
            ],
        ),
        migrations.CreateModel(
            name='Mrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Position')),
                ('m_total', models.FloatField(verbose_name='Total measurement. Equals efficiency of Drecord')),
                ('label', models.CharField(blank=True, max_length=30, null=True, verbose_name='Etiqueta')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_mrecord', to='gbudgets.Crecord')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mrecord', to='gbudgets.Crecord')),
            ],
        ),
        migrations.CreateModel(
            name='Mrecord_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Subtotal parcial'), (2, 'Subtotal acumulado'), (3, 'Expresi\xf3n')], null=True, verbose_name='Type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment or expression. Depending on TYPES')),
                ('id_bim', models.CharField(blank=True, max_length=200, null=True, verbose_name='BIM identifier')),
                ('units', models.FloatField(blank=True, null=True, verbose_name='Number of units')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('mrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Mrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Qrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Scope statement section code')),
                ('paragraph_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Scope statement paragraph code')),
            ],
        ),
        migrations.CreateModel(
            name='Rrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='Tipo de residuo')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rrecord', to='gbudgets.Crecord')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_rrecord', to='gbudgets.Crecord')),
            ],
        ),
        migrations.CreateModel(
            name='Rrecord_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(choices=[('r', 'Rendimiento'), ('rp', 'Porcentaje total de residuo de colocaci\xf3n')], default='r', max_length=4, verbose_name='Caracter\xedstica del residuo')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor de la propiedad')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Measurement unit')),
                ('rrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Rrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=150, null=True, verbose_name='Data base editor')),
                ('version', models.CharField(default='FIEBDC-3/2016', max_length=100, verbose_name='Format file version')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('emisor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Computer program or company that created the BC3 file')),
                ('header', models.CharField(blank=True, max_length=200, null=True, verbose_name='General title of ROTULOS_IDENTIFICACION')),
                ('char_set', models.CharField(choices=[('cp1252', 'ANSI'), ('850', '850'), ('cp437', '437')], default='850', max_length=10, verbose_name='Char set')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Small description about this BC3')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Base de datos'), (2, 'Presupuesto'), (3, 'Certificaci\xf3n (a origen)'), (4, 'Actualizaci\xf3n de base de datos')], null=True, verbose_name='Type of information')),
                ('certification_number', models.IntegerField(blank=True, null=True, verbose_name='Order of the certification')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Date of the certification')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url where documents and images can be found')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget')),
            ],
        ),
        migrations.CreateModel(
            name='Vrecord_id_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sequential title')),
                ('vrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Vrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Wrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abbreviation of the geographical scope')),
                ('scope', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complete name of the geographical scope')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget')),
            ],
        ),
        migrations.CreateModel(
            name='Xrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_code', models.CharField(choices=[('ce', 'Coste energ\xe9tico (MJ)'), ('eCO2', 'Emisi\xf3n de CO2 (kg)'), ('m', 'Masa del elemento (kg)'), ('ler', 'C\xf3digo ler de la lista europea de residuos'), ('v', 'Volumen (m3)')], max_length=6, verbose_name='Code of the technical information')),
                ('value', models.CharField(choices=[('ce', 'Coste energ\xe9tico (MJ)'), ('eCO2', 'Emisi\xf3n de CO2 (kg)'), ('m', 'Masa del elemento (kg)'), ('ler', 'C\xf3digo ler de la lista europea de residuos'), ('v', 'Volumen (m3)')], max_length=16, verbose_name='Code of the technical information')),
                ('crecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord')),
            ],
        ),
        migrations.AddField(
            model_name='qrecord',
            name='abbrev',
            field=models.ManyToManyField(blank=True, to='gbudgets.Wrecord'),
        ),
        migrations.AddField(
            model_name='qrecord',
            name='crecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcrecord', to='gbudgets.Crecord'),
        ),
        migrations.AddField(
            model_name='jrecord',
            name='qrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Qrecord'),
        ),
        migrations.AddField(
            model_name='jrecord',
            name='rtf_file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jrecord_rtf_file', to='gbudgets.Budget_file'),
        ),
        migrations.AddField(
            model_name='erecord',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget'),
        ),
        migrations.AddField(
            model_name='drecord',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget'),
        ),
        migrations.AddField(
            model_name='drecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_drecord', to='gbudgets.Crecord'),
        ),
        migrations.AddField(
            model_name='drecord',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_drecord', to='gbudgets.Crecord'),
        ),
        migrations.AddField(
            model_name='crecord_prices',
            name='id_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Vrecord_id_label'),
        ),
        migrations.AddField(
            model_name='crecord',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Gbudget'),
        ),
        migrations.AddField(
            model_name='brecord',
            name='crecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord'),
        ),
        migrations.AddField(
            model_name='brecord',
            name='file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brecord_file', to='gbudgets.Budget_file'),
        ),
        migrations.AddField(
            model_name='arecord',
            name='crecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord'),
        ),
    ]
