# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krecord',
            options={'ordering': ['budget']},
        ),
        migrations.AlterModelOptions(
            name='vrecord',
            options={'ordering': ['budget']},
        ),
        migrations.AlterModelOptions(
            name='vrecord_id_label',
            options={'ordering': ['vrecord']},
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='CI',
            new_name='ci',
        ),
    ]
