# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0002_auto_20160726_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krecord',
            old_name='BI',
            new_name='bi',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='GG',
            new_name='gg',
        ),
    ]
