# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0003_auto_20160726_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krecord',
            old_name='BAJA',
            new_name='baja',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DRC',
            new_name='drc',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='IVA',
            new_name='iva',
        ),
    ]
