# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0004_auto_20160726_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krecord',
            old_name='DC',
            new_name='dc',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DFS',
            new_name='dfs',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DRS',
            new_name='drs',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DUO',
            new_name='duo',
        ),
    ]
