# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0005_auto_20160726_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krecord',
            old_name='DD',
            new_name='dd',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DES',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DI',
            new_name='di',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DN',
            new_name='dn',
        ),
    ]
