# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0006_auto_20160726_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krecord',
            old_name='DEC',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DIVISA',
            new_name='divisa',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DS',
            new_name='ds',
        ),
        migrations.RenameField(
            model_name='krecord',
            old_name='DSP',
            new_name='dsp',
        ),
    ]
