# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0007_auto_20160726_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brecord',
            name='crecord',
        ),
        migrations.RemoveField(
            model_name='brecord',
            name='file',
        ),
        migrations.DeleteModel(
            name='Brecord',
        ),
    ]
