# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0008_auto_20160726_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_code', models.CharField(max_length=22, verbose_name='New code for concept')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcrecord', to='gbudgets.Crecord')),
            ],
        ),
        migrations.CreateModel(
            name='Frecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Otros'), (1, 'Caracter\xedsticas t\xe9cnicas y de fabricaci\xf3n'), (2, 'Manual de colocaci\xf3n, uso y mantenimiento'), (3, 'Certificado/s de elementos y sistemas'), (4, 'Normativa y bibliograf\xeda'), (5, 'Tarifa de precios'), (6, 'Condiciones de venta'), (7, 'Carta de colores'), (8, '\xc1mbito de aplicaci\xf3n y criterios selecci\xf3n'), (9, 'C\xe1lculo de elementos y sistemas'), (10, 'Presentaci\xf3n, datos generales, objetivos, etc. de empresa'), (11, 'Certificado/s de empresa'), (12, 'Obras realizadas'), (13, 'Imagen')], verbose_name='Type of file')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='File description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Relative url')),
                ('crecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbudgets.Crecord')),
                ('file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brecord_file', to='gbudgets.Budget_file')),
            ],
        ),
    ]
