# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbudgets', '0009_brecord_frecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krecord',
            name='dfs',
            field=models.IntegerField(default=3, verbose_name='... factores de rendimiento de unidades de obra y de elementos compuestos.'),
        ),
    ]
