# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gproject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is it active?'),
        ),
    ]
