# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gentities', '0001_initial'),
        ('gprojects', '0005_auto_20160321_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gday',
            name='gcalendar',
        ),
        migrations.RemoveField(
            model_name='gtime_slot',
            name='gcalendar',
        ),
        migrations.RemoveField(
            model_name='gtime_slot',
            name='gday',
        ),
        migrations.AddField(
            model_name='gday',
            name='gentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gentities.Gentity'),
        ),
        migrations.AddField(
            model_name='gtime_slot',
            name='gentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gentities.Gentity'),
        ),
    ]
