# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gentities', '0001_initial'),
        ('gprojects', '0007_gday_gtime_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbaseline',
            name='gproject',
        ),
        migrations.RemoveField(
            model_name='gtask',
            name='gbaseline',
        ),
        migrations.AddField(
            model_name='gbaseline',
            name='gentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gentities.Gentity'),
        ),
        migrations.AddField(
            model_name='gbaseline',
            name='gtasks',
            field=models.ManyToManyField(blank=True, to='gprojects.Gtask'),
        ),
        migrations.AddField(
            model_name='gcalendar',
            name='gdays',
            field=models.ManyToManyField(blank=True, to='gprojects.Gday'),
        ),
        migrations.AddField(
            model_name='gcalendar',
            name='gtime_slots',
            field=models.ManyToManyField(blank=True, to='gprojects.Gtime_slot'),
        ),
        migrations.AddField(
            model_name='gproject',
            name='gbaselines',
            field=models.ManyToManyField(blank=True, to='gprojects.Gbaseline'),
        ),
        migrations.AddField(
            model_name='gtask',
            name='gentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gentities.Gentity'),
        ),
    ]
