# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0008_auto_20160321_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbaseline',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Is it the active one?'),
        ),
    ]
