# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gprojects', '0009_gbaseline_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gproject',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='allowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
