# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0012_auto_20160321_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='gproject',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='The project is removed'),
        ),
    ]
