# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0013_gproject_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting date'),
        ),
    ]
