# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0014_gproject_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbaseline',
            name='scale',
            field=models.IntegerField(blank=True, default=23, null=True, verbose_name='Width in pixels for unit of time'),
        ),
    ]
