# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0015_gbaseline_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtask',
            name='likely_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(1), null=True, verbose_name='Likely time'),
        ),
        migrations.AlterField(
            model_name='gtask',
            name='optimistic_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(1), null=True, verbose_name='Optimistic time'),
        ),
        migrations.AlterField(
            model_name='gtask',
            name='pessimistic_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(1), null=True, verbose_name='Pessimistic time'),
        ),
    ]
