# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0016_auto_20160323_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbaseline',
            name='gtasks',
        ),
        migrations.RemoveField(
            model_name='gtask',
            name='gentity',
        ),
        migrations.AddField(
            model_name='gtask',
            name='gbaseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gprojects.Gbaseline'),
        ),
    ]
