# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0018_auto_20160323_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gproject',
            old_name='allowed',
            new_name='gusers_edit',
        ),
    ]
