# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0024_auto_20160327_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtask',
            name='predecessors',
            field=models.ManyToManyField(blank=True, related_name='successors', to='gprojects.Gtask'),
        ),
    ]
