# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0025_auto_20160327_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtask',
            name='predecessors',
        ),
    ]
