# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0028_auto_20160327_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtask',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='gprojects.Gtask'),
        ),
        migrations.AlterField(
            model_name='gtask',
            name='predecessors',
            field=models.ManyToManyField(blank=True, to='gprojects.Gtask'),
        ),
    ]
