# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0030_auto_20160327_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtask',
            old_name='children',
            new_name='subtasks',
        ),
        migrations.AlterField(
            model_name='gbaseline',
            name='scale',
            field=models.IntegerField(blank=True, default=24, null=True, verbose_name='Width in pixels for unit of time'),
        ),
    ]
