# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0032_remove_gtask_predecessors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtask',
            name='dependencies',
        ),
    ]
