# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0033_remove_gtask_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtask_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.CharField(choices=[('FS', 'Finish to Start'), ('FF', 'Finish to Finish'), ('SS', 'Start to Start'), ('SF', 'Start to Finish')], default='FS', max_length=10, verbose_name='Type of dependency')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predecessor', to='gprojects.Gtask')),
                ('successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor', to='gprojects.Gtask')),
            ],
        ),
    ]
