# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0034_gtask_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtask',
            name='pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vertical position'),
        ),
    ]
