# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0036_auto_20160401_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtask',
            options={'ordering': ['pos']},
        ),
        migrations.RenameField(
            model_name='gtask',
            old_name='percentage_complete',
            new_name='progress',
        ),
    ]
