# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0039_auto_20160401_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbaseline',
            name='columns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of foundation columns occupied by the gantt chart'),
        ),
    ]
