# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0041_gtask_display_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtask',
            name='display_subtasks',
        ),
    ]
