# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0042_remove_gtask_display_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtask',
            name='display_subtasks',
            field=models.BooleanField(default=True, verbose_name='Display subtasks'),
        ),
    ]
