# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0044_remove_gtask_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtask',
            name='gtask_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gprojects.Gtask'),
        ),
    ]
