# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0045_gtask_gtask_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gcolumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(blank=True, null=True, verbose_name='Horizontal position')),
                ('content', models.CharField(choices=[('estimate_time_days', 'Duration'), ('early_start', 'Early start'), ('last_finish', 'Last Finish')], default='estimate_time_days', max_length=30, verbose_name='Content of the column')),
                ('gbaseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gprojects.Gbaseline')),
            ],
            options={
                'ordering': ['gbaseline'],
            },
        ),
    ]
