# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 06:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0047_auto_20160416_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time_days', 'Duration'), ('early_start', 'Early startborrar'), ('last_finish', 'Last Finishborrar'), ('ES', 'Early start'), ('LF', 'Last Finish')], default='estimate_time_days', max_length=30, verbose_name='Content of the column'),
        ),
        migrations.AlterField(
            model_name='gcolumn',
            name='pos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Horizontal position'),
        ),
    ]
