# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0049_auto_20160417_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time_days', 'Durationborrar'), ('DUR', 'Duration'), ('early_start', 'Early startborrar'), ('last_finish', 'Last Finishborrar'), ('ES', 'Early start'), ('LF', 'Last Finish')], default='DUR', max_length=30, verbose_name='Content of the column'),
        ),
    ]
