# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0050_auto_20160417_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtask',
            name='early_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Early start'),
        ),
        migrations.AddField(
            model_name='gtask',
            name='last_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Finish'),
        ),
    ]
