# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0054_remove_gtask_lf'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtask',
            name='lf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Finish'),
        ),
    ]
