# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 12:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0056_auto_20160417_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time_days', 'Duration'), ('early_start', 'Early start'), ('last_finish', 'Last Finish')], default='estimate_time_days', max_length=30, verbose_name='Content of the column'),
        ),
        migrations.AlterField(
            model_name='gcolumn',
            name='pos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Horizontal position'),
        ),
    ]
