# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0060_auto_20160420_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbaseline',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is it the active one?'),
        ),
    ]
