# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0062_auto_20160420_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting date'),
        ),
    ]
