# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0064_gbaseline_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcolumn',
            name='width',
            field=models.IntegerField(default=100, verbose_name='Width in px on screen'),
        ),
    ]
