# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0067_auto_20160421_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time', 'Estimate time'), ('early_start', 'Early start'), ('last_finish', 'Last Finish')], default='estimate_time', max_length=30, verbose_name='Content of the column'),
        ),
        migrations.AlterField(
            model_name='gcolumn',
            name='format',
            field=models.CharField(choices=[('null', 'Without format'), ('asDays', 'Duraci\xf3n en d\xedas'), ('datetime', 'Fecha y hora'), ('date', 'Fecha')], default='datetime', max_length=30, verbose_name='Format to be used with moment.js'),
        ),
    ]
