# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0068_auto_20160421_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcolumn',
            options={'ordering': ['gbaseline', 'pos']},
        ),
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time_days', 'Estimate time (d)'), ('early_start_date', 'Early start (date)'), ('early_start_datetime', 'Early start (datetime)'), ('last_finish_date', 'Last Finish (date)'), ('last_finish_datetime', 'Last Finish (datetime)'), ('gtask_name', 'Task name')], default='estimate_time', max_length=30, verbose_name='Content of the column'),
        ),
        migrations.AlterField(
            model_name='gcolumn',
            name='pos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Horizontal position'),
        ),
    ]
