# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 14:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0070_remove_gcolumn_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='pos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)], verbose_name='Horizontal position'),
        ),
    ]
