# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0071_auto_20160429_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='pos',
            field=models.IntegerField(default=0, verbose_name='Horizontal position'),
        ),
    ]
