# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0072_auto_20160429_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbaseline',
            name='columns',
            field=models.IntegerField(default=9, verbose_name='Number of foundation columns occupied by the gantt chart'),
        ),
    ]
