# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0073_auto_20160604_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='width',
            field=models.IntegerField(default=150, verbose_name='Width in px on screen'),
        ),
    ]
