# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0074_auto_20160606_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcolumn',
            name='align',
            field=models.CharField(choices=[('center', 'center'), ('left', 'left'), ('right', 'right')], default='center', max_length=30, verbose_name='Text align'),
        ),
    ]
