# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojects', '0075_gcolumn_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcolumn',
            name='content',
            field=models.CharField(choices=[('estimate_time_days', 'Estimate time (d)'), ('early_start_date', 'Early start (date)'), ('early_start_datetime', 'Early start (datetime)'), ('last_finish_date', 'Last Finish (date)'), ('last_finish_datetime', 'Last Finish (datetime)'), ('gtask_name', 'Task name'), ('total_float', 'Total float'), ('free_float', 'Free float'), ('optimistic_time', 'Optimistic time'), ('likely_time', 'Likely time'), ('pessimistic_time', 'Pesimistic time')], default='estimate_time', max_length=30, verbose_name='Content of the column'),
        ),
    ]
